services:
  controle_aluguel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: controle_aluguel_php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage
      - ./.env:/var/www/html/.env
      - ./public/build:/var/www/html/public/build
    networks:
      - cnetwork
      - internal

  nginx:
    image: nginx:alpine
    container_name: controle_aluguel_nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - controle_aluguel
    networks:
      - cnetwork
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controle_aluguel.rule=Host(`controle-aluguel.higorsilva.dev`)"
      - "traefik.http.routers.controle_aluguel.entrypoints=websecure"
      - "traefik.http.routers.controle_aluguel.tls.certresolver=myresolver"
      - "traefik.http.services.controle_aluguel.loadbalancer.server.port=80"

networks:
  cnetwork:
    external: true
  internal:
    driver: bridge
