services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONTAINER_ROLE=ALL
    volumes:
      - ./storage:/var/www/app/storage
      - ./public/storage:/var/www/app/public/storage
    networks:
      - cnetwork
    # ports:
    #   - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controle_aluguel.rule=Host(`controle-aluguel.higorsilva.dev`)"
      - "traefik.http.routers.controle_aluguel.entrypoints=websecure"
      - "traefik.http.routers.controle_aluguel.tls.certresolver=myresolver"
      - "traefik.http.services.controle_aluguel.loadbalancer.server.port=8080"
networks:
  cnetwork:
    external: true
